### ISSUE TITLE
自分の Sokuseki を他者と共有したい

### ISSUE THREAD

**Issue by june29** [sokusekiya/sokuseki#129]
### 概要

- 現状、自分の Sokuseki しか見えない設計になっている
  - ものによっては誰にでも見えてよいわけではないので、意図的にそうしている
- ふりかえり会などで、他者と共有したいシチュエーションがある

### 考えること

- 安易に `/@june29` みたいな `users#show` のページをつくるわけにはいかない
  - GitHub 上で権限を管理しているのに、それを無視して情報を露出させることになる
- 「この人に見せちゃマズいものはない」みたいな状況なら、一時的に有効な共有 URL とかを発行して相手に渡せばいいのかもしれない？

**Comment by osamtimizer** [comment]
@june29 と口頭で話した内容をシェアします

## 実現したいこと

下記のように、表示可能な期間の横に一時共有用のURLを発行するリンクを設置します。
![image](https://user-images.githubusercontent.com/571988/64249105-d8e79d80-cf4d-11e9-87fb-f29237713c35.png)

## 実現のためにやること

`SharedLink`といった感じの名前のモデルを用意します。

`user has_many :shared_links`として、テーブルには以下のような情報を含めます。

|id|user_id|expire_at|on|token|
|---|---|---|---|---|
|Int|Int|dateTime|String|String|
|1|1|2019-09-04 20:30:00 +0900|2018-2nd|"random_text"|


`hostname/activities/on/term?token=random_text`としてアクセスした時に、トークンのパラメータがあればそれがDBに保存されているかをチェックし、一致かつ失行前であればそのトークンを発行したユーザーのアクティビティが見れるようになります。
安全のため、トークンは最長30分〜1時間程度で失行させる予定です。

「誰のアクティビティを表示しているか」がわかるように、アクティビティのページにはユーザーIDを表示します。
![image](https://user-images.githubusercontent.com/571988/64249561-ec473880-cf4e-11e9-8409-8ccaa0f03b35.png)

**Comment by osamtimizer** [comment]
https://github.com/sokusekiya/sokuseki/pull/169
マージされたのでCloseします
