### ISSUE TITLE
Dockerイメージの公開範囲を変更したい

### ISSUE THREAD

**Issue by pyama86** [sokusekiya/sokuseki#534]
時間が遅いからissueにしとく。
https://github.com/orgs/sokusekiya/packages/container/sokuseki/settings

sokusekiのcontainerイメージの公開範囲をpublicにしてほしいす。adminじゃないとできなさそう。

@june29

**Comment by june29** [comment]
Public にしました！

![Package_sokuseki](https://user-images.githubusercontent.com/3970/215304527-bd589e87-50cf-4248-8f5c-939f846272f3.png)

**Comment by pyama86** [comment]
わーい１
